name: Bazel build and test
on:
  pull_request:
    branches:
      - master
jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1

      - name: Version
        run: bazel version

      - name: Bazel build
        run: bazel build ...

      - name: Bazel test
        run: bazel test ... --test_output=streamed